# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Inke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inke
  pod 'SDWebImage', '~> 3.8.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension'
  pod 'SnapKit', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'IGListKit', '~> 3.0'
end
